name: Interactables
main: com.qwertyness.interactables.Interactables
version: 1.1.1
description: Interactables API
author: Qwertyness

commands:
  interactable:
    description: The base command for all Interactables plugins.